apply plugin: 'com.android.application'

android {
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.trustbank"
        minSdkVersion 29
        targetSdkVersion 34
        versionCode 4
        versionName "1.0.1"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        lintOptions {
            checkReleaseBuilds false
            abortOnError false
        }

        buildConfigField "String", "aes_key" ,'"AES"'
        buildConfigField "String", "pkcs7_key" ,'"AES/ECB/PKCS7Padding"'
        buildConfigField "String", "nop_key" ,'"AES/ECB/NoPadding"'
        buildConfigField "String", "enc_key" ,'"AP87TsvPTi2Aul1ipZrT3J4fNm4/LbhNLoX0i2WogFQ="'
        buildConfigField "String", "api_key" ,'"7jth/XWjfImtF4xY9TLYQbTZJAfC8ZiiZa5jfzOf3rM="'
        buildConfigField "String", "iv" ,'"0000000000000000"'
        buildConfigField "String", "no_pkcs7_key" ,'"AES/GCM/NoPadding"'
        buildConfigField "String", "IP" ,'"https://59.95.101.93:8079"'
    }

    signingConfigs {
        release {
            // Configure your signing information here
            storeFile file('mBankJKS.jks')
            storePassword 'tssipl'
            keyAlias 'tssipl'
            keyPassword 'tssipl'
            enableV3Signing true
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    flavorDimensions "content"
    productFlavors {
        trustmbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".trustmbank"
            versionName "1.0.32"
            versionCode 32
            resValue "string", "app_name", "NBFC_mbank_Test"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_launcher",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        sadhnambank {
            applicationId "com.trustbank"
            applicationIdSuffix ".sadhnambank"
            versionName "1.0.5"
            versionCode 6
            resValue "string", "app_name", "SSB Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/sadhna_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        pucbmbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".pucbmbank"
            versionName "1.1.4" //Live VERSION 5/11/2022
            versionCode 18       //Live Version.5/11/2022
            resValue "string", "app_name", "PUCB Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/puc_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        pdccbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".pdccbank"
            versionName "1.1.3"
            versionCode 6
            resValue "string", "app_name", "PDCC Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/pdcc_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        bucb {
            applicationId "com.trustbank"
            applicationIdSuffix ".bucbank"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "BUCB Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_brahmpuri_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        shivajibank {
            applicationId "com.trustbank"
            applicationIdSuffix ".shivajibank"
            versionName "1.0.4"
            versionCode 5
            resValue "string", "app_name", "SHIVAJI BANK MB"
            manifestPlaceholders = [
                    appIcon: "@drawable/shivaji_bank_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        vmucbbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".vmucbbank"
            versionName "1.0.8"  //(1.0.2)update with domain 25/04/2022  //1.0.4 --25/05/2022(sessionmanager key issue)
            versionCode 9
            resValue "string", "app_name", "M-Pay VMUCB"
            manifestPlaceholders = [
                    appIcon: "@drawable/logo_vmucb_mpay",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        punepeoplesbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".punepeoplesbank"
            versionName "1.0.9"
            versionCode 11
            resValue "string", "app_name", "PPCO Mobile App"
            manifestPlaceholders = [
                    appIcon: "@drawable/ppc_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        trustdemombankapp {
            applicationId "com.trustbank"
            applicationIdSuffix ".trustdemombankapp"
            versionName "1.0.6"
            versionCode 7
            resValue "string", "app_name", "MBank Dev"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_launcher",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        gondiamahilabank {
            applicationId "com.trustbank"
            applicationIdSuffix ".gondiamahilabank"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Mahila Urban Co-Opp Bank Gondia MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/gondia_mahila_bank",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        smritibank {
            applicationId "com.trustbank"
            applicationIdSuffix ".smritimbank"
            versionName "1.0.12"
            versionCode 13
            resValue "string", "app_name", "Smriti MBank Application"
            manifestPlaceholders = [
                    appIcon: "@drawable/smriti_bank",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        manndeshibank {
            applicationId "com.trustbank"
            applicationIdSuffix ".manndeshibank"
            versionName "1.0.1"
            versionCode 2
            resValue "string", "app_name", "Mann Deshi M-Connect Banking"
            manifestPlaceholders = [
                    appIcon: "@drawable/mandeshi_bank_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        hedgewarmbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".hedgewarmbank"
            versionName "1.0.2"
            versionCode 3
            resValue "string", "app_name", "Dr.Hedgewar MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/hedgewar_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        janataajarambank {
            applicationId "com.trustbank"
            applicationIdSuffix ".janataajarambank"
            versionName "1.0.4"
            versionCode 6
            resValue "string", "app_name", "Janata Bank Ajara"
            manifestPlaceholders = [
                    appIcon: "@drawable/janata_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        parijatmbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".parijatmbank"
            versionName "1.0.9"
            versionCode 10
            resValue "string", "app_name", "Parijat MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/parijat_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        mdccmbank { //UnUsed.
            applicationId "com.trustbank"
            applicationIdSuffix ".mdccmbank"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "MDCC MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/mdcc_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        kucbmbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".kucbmbank"
            versionName "1.0.4"
            versionCode 5
            resValue "string", "app_name", "KUCB Mpassbook"
            manifestPlaceholders = [
                    appIcon: "@drawable/kucb_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        anuradhambankbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".anuradhambankbank"
            versionName "1.0.3"
            versionCode 4
            resValue "string", "app_name", "Anuradha Bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/anuradha_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }


        vnspmmbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".vnspmmbank"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "VNSPM MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/vnspm_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        mdccmbankapp {
            applicationId "com.trustbank"
            applicationIdSuffix ".mdccmbankapp"
            versionName "1.0.5"
            versionCode 6
            resValue "string", "app_name", "MDCC MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/mdcc_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        nccsmbankapp {
            applicationId "com.trustbank"
            applicationIdSuffix ".nccsmbankapp"
            versionName "1.0.2"
            versionCode 3
            resValue "string", "app_name", "TNCCSL MPASSBOOK"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_nccs_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        motimbankapp {
            applicationId "com.trustbank"
            applicationIdSuffix ".motimbankapp"
            versionName "1.0.1"
            versionCode 2
            resValue "string", "app_name", "Moti Urban MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_moti_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }


        nagpursahakarimbankapp {
            applicationId "com.trustbank"
            applicationIdSuffix ".nagpursahakarimbankapp"
            versionName "1.0.2"
            versionCode 3
            resValue "string", "app_name", "Nagpur Sahakari MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_launcher",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
        itparkbank {
            applicationId "com.trustbank"
            applicationIdSuffix ".itparkbank"
            versionName "1.0.2"
            versionCode 4
            resValue "string", "app_name", "It park bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_launcher",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
        cucbmbank{
            applicationId "com.trustbank"
            applicationIdSuffix ".cucbmbank"
            versionName "1.0.2"
            versionCode 3
            resValue "string", "app_name", "CUCB MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/cucb_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
        //Lokmangal Sahakari Patsanstha Maryadit Asgaon

        lymsbank{
            applicationId "com.trustbank"
            applicationIdSuffix ".lymsbank"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Lokmangal Sahakari Patsanstha Maryadit Asgaon"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_lspma_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }


        //Ambika Mahila Sahakari Bank
        ambikamahilasahakarimbank{
            applicationId "com.trustbank"
            applicationIdSuffix ".ambikamahilasahakarimbank"
            versionName "1.0.2"
            versionCode 3
            resValue "string", "app_name", "Ambika Mahila Sahakari MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_ambika_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Balitikuri Co-Operative Bank Ltd
        balitikurimbank{
            applicationId "com.trustbank"
            applicationIdSuffix ".balitikurimbank"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Balitikuri Mpassbook"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_balitikuri_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Mpassbook CDCC
        cdccbankmpassbook{
            applicationId "com.trustbank"
            applicationIdSuffix ".cdccbank"
            versionName "1.0.1"
            versionCode 3
            resValue "string", "app_name", "THE CHANDRAPUR DISTRICT CENTRAL CO-OP BANK LTD"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_cdcc_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
        //ashirwadmahilabank
        ashirwadmahila{
            applicationId "com.trustbank"
            applicationIdSuffix ".ashirwadmahila"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Ashirwad Mahila Nagari Sahakari Bank LTD"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_ashirwadmahila_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
        //Amarnath Bank
        amarnath{
            applicationId "com.trustbank"
            applicationIdSuffix ".amarnath"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Amarnath MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_amarnath_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
        //Latur urban bank
        latur{
            applicationId "com.trustbank"
            applicationIdSuffix ".latur"
            versionName "1.0.7"
            versionCode 8
            resValue "string", "app_name", "Latur Urban Bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_latur_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //shramjivipatsanstha
        shramjivi{
            applicationId "com.trustbank"
            applicationIdSuffix ".shramjivi"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Shramjivi MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_shramji_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //bhausaheb sahakari bank ltd
        bhausahebsahakari{
            applicationId "com.trustbank"
            applicationIdSuffix ".bhausahebsahakari"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Bhausaheb Sahakari Bank ltd"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_bhausaheb_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }


//        BORGAON URBAN CO OP CREDIT SOCIETY LTD
        borgaonurban{
            applicationId "com.trustbank"
            applicationIdSuffix ".borgaonurban"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "BORGAON URBAN MBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_borgaon_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        // Bantra Co operative Bank
        bantra{
            applicationId "com.trustbank"
            applicationIdSuffix ".bantra"
            versionName "1.0.3"
            versionCode 3
            resValue "string", "app_name", "Bantra Co operative Bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/bantra_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        // Ratnasundar Bank
        ratnasundar{
            applicationId "com.trustbank"
            applicationIdSuffix ".ratnasundar"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Ratnasundar Bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ratnasundar2",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Hooghly co operative Bank
        hoogly{
            applicationId "com.trustbank"
            applicationIdSuffix ".hoogly"
            versionName "1.0.1"
            versionCode 2
            resValue "string", "app_name", "Hooghly co operative Bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/hoogly_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //subhedar society
        subhedar{
            applicationId "com.trustbank"
            applicationIdSuffix ".subhedar"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "New Subhedar Society"
            manifestPlaceholders = [
                    appIcon: "@drawable/subhedar_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Shikshak Bank kolhapur
        shikshak{
            applicationId "com.trustbank"
            applicationIdSuffix ".shikshak"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Shikshak Bank kolhapur"
            manifestPlaceholders = [
                    appIcon: "@drawable/shikshak",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        // Veerseva bank
        veerseva{
            applicationId "com.trustbank"
            applicationIdSuffix ".shriveerseva"
            versionName "1.0.4"
            versionCode 5
            resValue "string", "app_name", "Shri Veershaiv Co-Op Bank Ltd."
            manifestPlaceholders = [
                    appIcon: "@drawable/veerseva",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        Gautam{
            applicationId "com.trustbank"
            applicationIdSuffix ".gautam"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Gautam Bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/gautambank",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
        //Bhausaheb Birajdar Urban Co-operative Bank Ltd., Omerga
        bhausahebbirajdar{
            applicationId "com.trustbank"
            applicationIdSuffix ".bhausahebbirajdar"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Bhausaheb Birajdar Urban Co-operative Bank Ltd., Omerga"
            manifestPlaceholders = [
                    appIcon: "@drawable/bhausahebbirajdar",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
        //Konkan Fincap Co-Operative Bank
        konkan{
            applicationId "com.trustbank"
            applicationIdSuffix ".konkan"
            versionName "1.0.3"
            versionCode 4
            resValue "string", "app_name", "Konkan Fincap Co-Operative Bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/kfcb_logo_new",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Priyadarshani Urban co op Bank
        priyadarshani{
            applicationId "com.trustbank"
            applicationIdSuffix ".priyadarshani"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Priyadarshani Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/priydarshani",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Dr.Panjabrao Deshmukh Urban Co-operative Bank
        panjabrao{
            applicationId "com.trustbank"
            applicationIdSuffix ".panjabrao"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Dr.Panjabrao Deshmukh Urban Co-operative Bank"
            manifestPlaceholders = [
                    appIcon: "@drawable/panjabrao_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Bramhapuri Urban Co-op Bank Ltd.
        bramhapuri{
            applicationId "com.trustbank"
            applicationIdSuffix ".bramhapuri"
            versionName "1.0.3"
            versionCode 4
            resValue "string", "app_name", "Bramhapuri  Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/bramhapuri_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Palus Mbank
        palus{
            applicationId "com.trustbank"
            applicationIdSuffix ".palus"
            versionName "1.0.3"
            versionCode 4
            resValue "string", "app_name", "Palus Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/palus_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //The Prathamik Shikshak Sahakari Bank Ltd., Kolhapur
        prathamik{
            applicationId "com.trustbank"
            applicationIdSuffix ".prathamik"
            versionName "1.0.1"
            versionCode 2
            resValue "string", "app_name", "Prathamik Shikshak Sahakari Bank Mpassbook"
            manifestPlaceholders = [
                    appIcon: "@drawable/prathamik_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Osmanabad Janata Sahakari Bank Ltd, Osmanabad
        osmanabad{
            applicationId "com.trustbank"
            applicationIdSuffix ".osmanabad"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Osmanabad Mpassbook"
            manifestPlaceholders = [
                    appIcon: "@drawable/osmanabad_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Navin Subhedar
        navinsubhedarmbank{
            applicationId "com.trustbank"
            applicationIdSuffix ".navinsubhedarmbank"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Navin Subhedar Mpassbook"
            manifestPlaceholders = [
                    appIcon: "@drawable/ic_subhedar_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Bilaspur
        bilaspur{
            applicationId "com.trustbank"
            applicationIdSuffix ".bilaspur"
            versionName "1.0.1"
            versionCode 2
            resValue "string", "app_name", "Bilaspur Nagrik mBank"
            manifestPlaceholders = [
                    appIcon: "@drawable/bilaspur_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Gadchiroli DCC Bank Ltd. Gadchiroli
        gdccmbank{
            applicationId "com.trustbank"
            applicationIdSuffix ".gdccmbank"
            versionName "1.0.1"
            versionCode 2
            resValue "string", "app_name", "GDCC Mpassbook"
            manifestPlaceholders = [
                    appIcon: "@drawable/gdcc_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Ahmendnagar Prathamik Shikshak Bank
        ahmednagar{
            applicationId "com.trustbank"
            applicationIdSuffix ".ahmednagar"
            versionName "1.0.2"
            versionCode 3
            resValue "string", "app_name", "AZPSS Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/ahmednagar_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Alavi co operative bank limited
        alavi{
            applicationId "com.trustbank"
            applicationIdSuffix ".alavi"
            versionName "1.0.2"
            versionCode 5
            resValue "string", "app_name", "Alavi Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/alavi_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Alavi co operative bank limited
        alavimbank{
            applicationId "com.trustbank"
            applicationIdSuffix ".alavimbank"
            versionName "1.0.1"
            versionCode 2
            resValue "string", "app_name", "Alavi Mbank"
            manifestPlaceholders = [
                    appIcon: "@drawable/alavi_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        //Union Co op. Mpassbook
        unionmbank{
            applicationId "com.trustbank"
            applicationIdSuffix ".unionmbank"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "Union Co op. Mpassbook"
            manifestPlaceholders = [
                    appIcon: "@drawable/union_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }

        krishnaparaspar  {
            applicationId "com.trustbank"
            applicationIdSuffix ".mkrishnaparaspar"
            versionName "1.0.0"
            versionCode 1
            resValue "string", "app_name", "KRISHNAPARASPAR NIDHI LIMITED"
            manifestPlaceholders = [
                    appIcon: "@drawable/nidhibank_logo",google_maps_key:"AIzaSyCLFw6IjAiZJifQlxQtdZuH839FyyUgfrg"
            ]
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.core:core:1.3.2'
    implementation 'androidx.vectordrawable:vectordrawable-animated:1.1.0'
    implementation 'com.google.android.material:material:1.2.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation files('libs/android-zoom-view.jar')
    implementation files('libs/jsoup-1.6.0.jar')
    implementation project(':library')
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    implementation 'com.github.bumptech.glide:annotations:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    implementation project(':floatingbuttonlibrary')
    implementation files('libs/jxl-2.6.12.jar')
    implementation files('libs/itextg-5.5.8.jar')
    implementation "com.madgag.spongycastle:prov:1.54.0.0"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.jakewharton:butterknife:10.0.0'
    implementation 'com.google.android.gms:play-services-auth:19.0.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:17.5.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.0.0'
    implementation 'com.github.smart-fun:XmlToJson:1.5.3'
    implementation 'com.google.android.gms:play-services-vision:20.1.3'
    implementation 'com.google.zxing:core:3.3.3'
    implementation 'androidx.security:security-crypto:1.0.0'
    implementation 'androidx.biometric:biometric:1.0.1'
    implementation 'com.google.android.play:app-update:2.1.0'
}